[template.environment]
    REACT_APP_FOR_SALE = "true or false if the domain is for sale"
    REACT_APP_IN_USE = "true or false if the domain is in use"
    REACT_APP_DOMAIN = "the domain name this is being deployed to"
    REACT_APP_CONTACT_EMAIL = "your email address"